//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallVysota.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public Information()
        {
            this.RentMall = new HashSet<RentMall>();
        }
    
        public int ID { get; set; }
        public int IDUserAgreement { get; set; }
        public string AboutApp { get; set; }
    
        public virtual UserAgreement UserAgreement { get; set; }
        public virtual ICollection<RentMall> RentMall { get; set; }
    }
}
