//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallVysota.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MallVysotaEntities : DbContext
    {
        public MallVysotaEntities()
            : base("name=MallVysotaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Information> Information { get; set; }
        public DbSet<RentMall> RentMall { get; set; }
        public DbSet<Rooms> Rooms { get; set; }
        public DbSet<RoomStatus> RoomStatus { get; set; }
        public DbSet<RoomTypes> RoomTypes { get; set; }
        public DbSet<UserAgreement> UserAgreement { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
