//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallVysota.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.RentMall = new HashSet<RentMall>();
            this.Users1 = new HashSet<Users>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int IDRoomType { get; set; }
        public Nullable<int> IDRenter { get; set; }
        public Nullable<System.DateTime> RentDateStart { get; set; }
        public Nullable<System.DateTime> RentDateEnd { get; set; }
        public int IDRoomStatus { get; set; }
        public string Photo { get; set; }
        public decimal MonthPrice { get; set; }
        public Nullable<decimal> YearPrice { get; set; }
    
        public virtual ICollection<RentMall> RentMall { get; set; }
        public virtual RoomStatus RoomStatus { get; set; }
        public virtual RoomTypes RoomTypes { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Users> Users1 { get; set; }
    }
}
