//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallVysota.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAgreement
    {
        public UserAgreement()
        {
            this.Information = new HashSet<Information>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Information> Information { get; set; }
    }
}
