//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallVysota.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Rooms = new HashSet<Rooms>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Facility { get; set; }
        public string Phone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> IDRentedRooms { get; set; }
    
        public virtual ICollection<Rooms> Rooms { get; set; }
        public virtual Rooms Rooms1 { get; set; }
    }
}
